import type { NextApiRequest, NextApiResponse } from 'next'
import { getAuth } from '@clerk/nextjs/server'
import { generateOutfitsForUser } from '../../../ai/outfit'
import { connectToDatabase } from '../../../lib/mongodb'
import Outfit from '../../../models/Outfit'

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  try {
    if (req.method !== 'POST') return res.status(405).end()

    const auth = getAuth(req)
    const userId = auth.userId
    if (!userId) return res.status(401).json({ error: 'Unauthorized' })

    const { occasion, weather, preferences, save = false, mode = 'hybrid' } = req.body
    const generated = await generateOutfitsForUser(userId, { occasion, weather, preferences, mode })

    if (!save) return res.status(200).json({ outfits: generated })

    await connectToDatabase()
    const outfits = await Outfit.insertMany(generated.map((outfit, index) => ({
      userId,
      title: `${occasion || 'Smart'} outfit ${index + 1}`,
      occasion: occasion || 'casual',
      items: outfit.items.map((item) => ({ clothing: item.id })),
      score: outfit.score,
      explanation: outfit.explanation,
      tags: outfit.tags,
      colorAnalysis: outfit.colorAnalysis || 'Generated by FitFusion color harmony scoring.',
      breakdown: outfit.breakdown || {}
    })))

    return res.status(201).json({ outfits })
  } catch (error: any) {
  console.error('OUTFIT AI ERROR:', error)

  return res.status(500).json({
    error: error?.message || 'AI outfit generation failed'
  })
}}
