import type { NextApiRequest, NextApiResponse } from 'next'
import { getAuth } from '@clerk/nextjs/server'
import { connectToDatabase } from '../../../lib/mongodb'
import Clothing from '../../../models/Clothing'
import Outfit from '../../../models/Outfit'
import CalendarOutfit from '../../../models/CalendarOutfit'
import TravelTrip from '../../../models/TravelTrip'
import { buildChecklist } from '../../../lib/travel/checklistEngine'
import { generatePackingList } from '../../../lib/travel/packingEngine'
import { planLaundry } from '../../../lib/travel/laundryPlanner'
import { scheduleTripOutfits } from '../../../lib/travel/outfitScheduler'
import { normalizeTripInput } from '../../../lib/travel/tripPlanner'
import { buildTravelAdvice } from '../../../lib/travel/travelAdvisor'
import { getTravelWeather } from '../../../lib/travel/weatherAnalyzer'

function setPrivateNoStore(res: NextApiResponse) {
  res.setHeader('Cache-Control', 'private, no-store, max-age=0, must-revalidate')
  res.setHeader('Vary', 'Cookie')
}

function parseDate(value: string) {
  const date = new Date(value)
  date.setHours(12, 0, 0, 0)
  return date
}

async function createCalendarLinks(userId: string, scheduled: any[], travelStyle: string, destination: string) {
  const primaryByDate = new Map<string, any>()
  for (const entry of scheduled) {
    if (entry.slot === 'morning' && !primaryByDate.has(entry.date)) primaryByDate.set(entry.date, entry)
  }

  for (const entry of primaryByDate.values()) {
    const generated = entry.outfit
    const date = parseDate(entry.date)
    const outfit = await Outfit.create({
      userId,
      title: `${travelStyle || 'travel'} outfit for ${entry.date}`,
      occasion: generated.occasion || 'travel',
      items: (generated.items || []).map((item: any) => ({ clothing: item._id || item.id, role: item.role })),
      score: generated.score || 0,
      explanation: generated.explanation,
      colorAnalysis: generated.colorAnalysis,
      breakdown: generated.breakdown || {},
      tags: generated.tags || [],
      outfitKey: generated.outfitKey,
      confidence: generated.confidence,
      method: 'travel',
      plannedFor: date,
      isFavorite: false
    }).catch(() => null)
    if (!outfit) continue
    await CalendarOutfit.findOneAndUpdate(
      { userId, date, occasion: generated.occasion || 'travel' },
      {
        userId,
        date,
        outfitId: outfit._id,
        occasion: generated.occasion || 'travel',
        weather: {
          temperature: entry.weather?.temperature,
          condition: entry.weather?.condition,
          suggestion: entry.weather?.advice,
          source: entry.weather?.source || 'trip-planner'
        },
        notes: `Trip: ${destination}. Primary travel outfit generated by packing assistant for ${travelStyle}.`,
        status: 'planned'
      },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    ).catch(() => null)
  }
}

async function buildPlan(userId: string, body: any) {
  const trip = normalizeTripInput(body)
  const wardrobe = await Clothing.find({ userId }).limit(1000).lean()
  const weather = await getTravelWeather({ destination: trip.destination, dates: trip.dates, lat: trip.lat, lon: trip.lon })
  const packingList = generatePackingList({ wardrobe: wardrobe as any[], days: trip.days, travelStyle: trip.travelStyle, activities: trip.activities, weather })
  const scheduledOutfits = scheduleTripOutfits({ wardrobe: wardrobe as any[], dates: trip.dates, weather, travelStyle: trip.travelStyle, activities: trip.activities })
  const laundry = planLaundry(trip.days)
  const advice = buildTravelAdvice({ weather, packingList, travelStyle: trip.travelStyle })
  return {
    ...trip,
    weather,
    packingList,
    scheduledOutfits,
    laundry,
    advice,
    progress: { packed: 0, total: packingList.length, percent: 0 }
  }
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  setPrivateNoStore(res)
  if (!['GET', 'POST', 'PATCH', 'DELETE'].includes(req.method || '')) {
    res.setHeader('Allow', ['GET', 'POST', 'PATCH', 'DELETE'])
    return res.status(405).end(`Method ${req.method} Not Allowed`)
  }

  const { userId } = getAuth(req)
  if (!userId) return res.status(401).json({ error: 'Unauthorized' })

  try {
    await connectToDatabase()
  } catch {
    if (req.method === 'GET') return res.status(200).json([])
    return res.status(503).json({ error: 'Database unavailable. Please try again shortly.' })
  }

  try {
    if (req.method === 'GET') {
      const trips = await TravelTrip.find({ userId }).sort({ startDate: -1 }).lean()
      return res.status(200).json(trips)
    }

    if (req.method === 'POST') {
      const duplicateId = typeof req.body?.duplicateId === 'string' ? req.body.duplicateId : ''
      if (duplicateId) {
        const source = await TravelTrip.findOne({ _id: duplicateId, userId }).lean()
        if (!source) return res.status(404).json({ error: 'Trip not found' })
        const copy = await TravelTrip.create({
          userId,
          destination: `${source.destination} Copy`,
          startDate: source.startDate,
          endDate: source.endDate,
          purpose: source.purpose,
          activities: source.activities,
          transportation: source.transportation,
          travelStyle: source.travelStyle,
          plan: source.plan,
          checklist: (source.checklist || []).map((item: any) => ({ ...item, packed: false }))
        })
        return res.status(201).json(copy)
      }

      const plan = await buildPlan(userId, req.body)
      const checklist = buildChecklist(plan.packingList)
      const saved = await TravelTrip.create({
        userId,
        destination: plan.destination,
        startDate: parseDate(plan.startDate),
        endDate: parseDate(plan.endDate),
        purpose: plan.purpose,
        activities: plan.activities,
        transportation: plan.transportation,
        travelStyle: plan.travelStyle,
        plan,
        checklist
      })
      await createCalendarLinks(userId, plan.scheduledOutfits, plan.travelStyle, plan.destination).catch(() => null)
      return res.status(201).json(saved)
    }

    if (req.method === 'PATCH') {
      const id = String(req.body?.id || '')
      const trip = await TravelTrip.findOne({ _id: id, userId })
      if (!trip) return res.status(404).json({ error: 'Trip not found' })
      if (req.body?.action === 'archive') trip.status = 'archived'
      else if (Array.isArray(req.body?.checklist)) trip.checklist = req.body.checklist
      else {
        const plan = await buildPlan(userId, { ...trip.toObject(), ...req.body })
        trip.set({
          destination: plan.destination,
          startDate: parseDate(plan.startDate),
          endDate: parseDate(plan.endDate),
          purpose: plan.purpose,
          activities: plan.activities,
          transportation: plan.transportation,
          travelStyle: plan.travelStyle,
          plan,
          checklist: buildChecklist(plan.packingList)
        })
        await createCalendarLinks(userId, plan.scheduledOutfits, plan.travelStyle, plan.destination).catch(() => null)
      }
      await trip.save()
      return res.status(200).json(trip)
    }

    const id = String(req.query.id || req.body?.id || '')
    const deleted = await TravelTrip.findOneAndDelete({ _id: id, userId })
    if (!deleted) return res.status(404).json({ error: 'Trip not found' })
    return res.status(200).json({ ok: true })
  } catch (error: any) {
    return res.status(500).json({ error: error?.message || 'Could not process trip' })
  }
}
